.PHONY: test

test:
	circleci local execute -e CIRCLE_PROJECT_REPONAME=$(shell basename $(shell pwd)) circleci local execute -e CIRCLE_PROJECT_REPONAME=$(shell basename $(shell pwd)) -e REDHAT_REGISTRY_SERVICE_ACCOUNT_USERNAME=${REDHAT_REGISTRY_SERVICE_ACCOUNT_USERNAME} -e REDHAT_REGISTRY_SERVICE_ACCOUNT_PASSWORD=${REDHAT_REGISTRY_SERVICE_ACCOUNT_PASSWORD} --job test
