---
- include_tasks: setup-Debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: setup-Archlinux.yml
  when: ansible_os_family == "Archlinux"

- include_tasks: setup-Redhat.yml
  when: ansible_os_family == "RedHat"

- name: Add nfsstat to PATH
  blockinfile:
    path: "{{ item }}"
    marker: "# {mark} Adds nfsstat to PATH"
    block: export PATH=/usr/sbin:$PATH
  loop:
    - ~{{ nfs_user }}/.bash_profile
    - ~{{ nfs_user }}/.bashrc
