---
- gather_facts: false
  hosts: all
  name: Prepare RedHat
  tasks:
    - name: Subscribe to RHN
      redhat_subscription:
        state: present
        username: "{{ lookup('env','REDHAT_REGISTRY_SERVICE_ACCOUNT_USERNAME') }}"
        password: "{{ lookup('env','REDHAT_REGISTRY_SERVICE_ACCOUNT_PASSWORD') }}"
        auto_attach: true

- become: true
  hosts: all
  name: Prepare
  tasks:
    - name: Create shell initialization files
      file:
        path: "{{ item }}"
        state: touch
      with_items:
        - ~/.bashrc
        - ~/.bash_profile
